Модули + шаблонизация + сборка SPA
frontend-park-mail-ru/2024_1_ResCogitans pull request #1
Opened 2024-03-03 19:22 UTC by exg0rd

2024-03-04 07:13 UTC, mzingwrld requested changes

2024-03-04 07:13 UTC, mzingwrld commented on public/styles.css
> +}
Давай разнесем styles.css:
- которые component-specific -> в каталоги с компонентами
- общие на весь проект в common.css
- все файлы импортировать в главный index.css на уровне index.js, например так:
`@import './components/Button/Button.css';`

2024-03-04 07:13 UTC, mzingwrld commented on public/index.html
> +    </div>
Стоит оставить один div с id, например, root или content - тут как душе угодно

Далее, сделать каталог pages или views, где будут .js файлы, которые рендерят контент страницы в этот div

Поверх всего этого нужно реализовать примитивный router, который будет в зависимости от route рисовать тот или иной view/page

2024-03-04 07:13 UTC, mzingwrld commented on src/components/Header/Header.js
> +        new Link(linkBlock, {label : 'Поддержка'}).render();
Тут можно относительно лейблов сделать перебор, например:

`['Альбомы', 'Отзывы', 'Поддержка'].forEach...`

А еще, это выглядит как отдельный метод, например, `renderLinksBlock()` - рекомендую посмотреть в сторону того, чтобы такие части объявлять в отдельные методы, тогда основной render() будет более чистым

2024-03-04 07:13 UTC, mzingwrld commented on src/components/Placelist/Placelist.js
> +        }
```suggestion
        data.forEach((placeData) => new Place(placelist, placeData.data).render());
```

2024-03-04 07:13 UTC, mzingwrld commented on src/index.js
> +new Placelist(search).render();
Тут, соответственно, оставить только получение одного элемента и инициацию роутера => роутер уже будет вызывать рендер нужной страницы

Плюс, будет классно, если будет проверка на наличие компонента

2024-03-04 07:13 UTC, mzingwrld commented on README.md
> +Будет собираться JSом на основе модулей с логикой работы элементов
Здесь нужно написать как запустить webpack в режиме разработки и как сделать сборку

2024-03-04 20:18 UTC, exg0rd commented on package.json
> +    "sass-loader": "^14.1.1",
Я добавил его, настроил в конфиге вебпака, пока не увидел разницу... Почитал про него, он шустрый

2024-03-04 20:19 UTC, exg0rd commented on package.json
> +    "prod": "webpack --mode production"
✅

2024-03-04 20:19 UTC, exg0rd commented on package.json
> +    "dev": "webpack --mode development",
✅

2024-03-04 20:26 UTC, exg0rd commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
✅  в CSS @font-face

2024-03-04 20:28 UTC, exg0rd commented on public/styles.css
> +    font-family: 'Roboto';
✅

2024-03-04 20:29 UTC, exg0rd commented on src/components/Button/Button.js
> +        this._class = _class; //css class
✅

2024-03-04 20:53 UTC, exg0rd commented on src/components/Button/index.js
> +export { default} from './Button'
✅ Поставил от airbnb, добавил два скрипта, один из них фиксит форматирование во всех файлах

2024-03-04 22:24 UTC, exg0rd commented on public/styles.css
> +}
✅

2024-03-04 22:27 UTC, exg0rd commented on src/components/Header/Header.js
> +        new Link(linkBlock, {label : 'Поддержка'}).render();
✅

Норм тема, буду думать, где еще так можно...

2024-03-04 22:29 UTC, exg0rd commented on src/components/Placelist/Placelist.js
> +        }
✅

2024-03-04 22:29 UTC, exg0rd commented on src/index.js
> +new Placelist(search).render();
Начал тут работать над этим..

2024-03-05 03:55 UTC, mzingwrld requested changes

2024-03-05 03:55 UTC, mzingwrld commented on README.md
> +4) npm run lint:fix - прогнать eslint с правкой и форматированием кода под кодстайл AirBnB
Тут лучше тоже разделить все по смыслу, не смешивая:

Я бы рекомендовал так:

1. Локальная разработка
 - npm i
 - npm run start
2. Сборка
 - npm i
 - npm run build
3. Форматирование:
 - npm run lint:fix

2024-03-05 03:55 UTC, mzingwrld commented on README.md
> +np
что-то лишнее затерялось

2024-03-05 03:55 UTC, mzingwrld commented on src/components/Button/Button.js
> +    this.className = className; // css class
комментарий лишний: и так ясно что за атрибут :)

2024-03-05 03:55 UTC, mzingwrld commented on src/components/Button/index.js
> +export { default } from './Button';
Я бы не рекомендовал плодить такие index.js файлы

Они со временем начинают бесить, а из пользы: только более короткий импорт, вместо /Button/Button просто Button..

2024-03-05 03:55 UTC, mzingwrld commented on src/components/Header/Header.css
> +}
В css файлах стоит тоже добавить переносы строк в конце файлов.

Можно также настроить линтер для css-а: можно посмотреть на `stylelint`

2024-03-05 03:55 UTC, mzingwrld commented on webpack.config.js
> +const ESLintPlugin = require('eslint-webpack-plugin');
а зачем тут eslint импортируется?

2024-03-05 03:55 UTC, mzingwrld commented on src/index.js
> +const root = document.getElementById('root');
все еще рекомендую проверить наличие root элемента - вдруг кто-то его уберет оттуда :)

2024-03-05 03:55 UTC, mzingwrld commented on package.json
> +    "sass-loader": "^14.1.1",
Фишка в том, что он быстрый, ага)

2024-03-05 03:55 UTC, mzingwrld commented on src/components/Button/index.js
> +export { default} from './Button'
@exg0rd, можно добавить в бэклог задачку на внедрение pre-commit хука, который будет автоматом линтить

а если есть ошибки в форматировании, то не даст закоммитить такой код

прям сейчас не стоит делать - будет время и желание, сделаете позже)

2024-03-05 04:01 UTC, mzingwrld requested changes

2024-03-05 04:01 UTC, mzingwrld commented on public/index.html
> +    <script src="bundle.js" defer></script>
Вопрос про defer свойство - зачем ты его указал, что оно делает?

2024-03-05 09:56 UTC, exg0rd commented on README.md
> +np
done

2024-03-05 09:56 UTC, exg0rd commented on src/components/Button/Button.js
> +    this.className = className; // css class
done

2024-03-05 10:05 UTC, exg0rd commented on src/components/Button/index.js
> +export { default } from './Button';
done, удалил их, поправил импорты, все работает

2024-03-05 10:05 UTC, exg0rd commented on src/components/Header/Header.css
> +}
в бэклог пока

2024-03-05 10:06 UTC, exg0rd commented on webpack.config.js
> +const ESLintPlugin = require('eslint-webpack-plugin');
проглядел, done

2024-03-05 10:24 UTC, exg0rd commented on src/index.js
> +const root = document.getElementById('root');
done

2024-03-05 10:28 UTC, exg0rd commented on public/index.html
> +    <script src="bundle.js" defer></script>
Так как мы работаем с домом, надо дождаться загрузки и разбора страницы на дом элементы, после чего уже запускать сам скрипт, то есть скачивание и выполнение скрипта не будет блокирующей операцией.

2024-03-05 15:07 UTC, mzingwrld requested changes

2024-03-05 15:07 UTC, mzingwrld commented on public/index.html
> +    <script src="bundle.js" defer></script>
Это может быть полезно для скриптов, которые не нужны прям сразу, а у нас это фактически весь нужный контент - я бы не откладывал его загрузку)

2024-03-05 15:13 UTC, mzingwrld approved these changes
Аппрув авансом небольшим поставил. Поправь минорное и можно сливать в main

2024-03-05 15:13 UTC, mzingwrld commented on .eslintignore
> +public/bundle.js
тут нужен перенос строки в конце файла

2024-03-05 15:13 UTC, mzingwrld commented on .gitignore
> +.vscode
и тут перенос строки

2024-03-05 15:13 UTC, mzingwrld commented on src/components/Button/Button.hbs
> +</button>
в линтер нужно включить .hbs файлы - должно тоже нормально отрабатывать, пусть автоматом тоже добавит перенос строки в конец файла ко всем .hbs

2024-03-05 19:41 UTC, exg0rd commented on public/index.html
> +    <script src="bundle.js" defer></script>
✓

2024-03-05 19:41 UTC, exg0rd commented on public/bundle.js
✓

2024-03-05 20:02 UTC, exg0rd commented on src/components/Button/Button.hbs
> +</button>
я попробовал разные варианты, пока не получилось, добавил переносы строк ручками

2024-03-06 05:01 UTC, merged