validation html+start js
frontend-park-mail-ru/2024_1_ResCogitans pull request #12
Opened 2024-03-15 22:29 UTC by exg0rd

Написана валидация через встроенную валидацию html форм + проверка совпадения пароля + кнопки показа пароля + форма на повтор пароля

2024-03-16 11:29 UTC, mzingwrld requested changes

2024-03-16 11:29 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +        passwordVisibility.children[0].src = "static/visible.svg";
Ну и, соответственно, сделать переиспользование в форме регистрации

2024-03-19 12:28 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.hbs
> +    <label id="error" class="err-link"></label>
Вообще наверно стоит сделать отдельный компонент для ссылок и для label

2024-03-19 14:49 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +    errorMessage.style.color = "red";
сделал

2024-03-19 20:59 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.hbs
> +        <input id="password" type="password" class="form-input" required maxlength="16" title="Пароль не может быть пустым и содержать пробелы" pattern="(?=.*\d)(?=.*[A-Z])(?!.*\s).{8,}">
вроде как получилось сделать норм регулярку)

2024-03-19 21:06 UTC, exg0rd commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +        this.renderError("Пароли не совпадают");
Вроде как все учел, навешен обработчик отслеживания ввода с клавиатуры в формах

2024-03-20 14:53 UTC, mzingwrld requested changes

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +      errorMessage.classList.add('active');
Более удачным неймингом будет `has-error`)

2024-03-20 14:53 UTC, mzingwrld commented on src/utils/validation.js
> +export function validate(inputText, type) {
Очень непонятно что такое 1, а что такое 2, когда видишь вызов функции. Лучше использовать объект в таком случае в качестве аргумента, чтобы получилось вот так: `vadlidate({input: inputText, type: 'password'})`

2024-03-20 14:53 UTC, mzingwrld commented on src/utils/validation.js
> +  export default validate;
не прогнал линтер - не хватает переноса строки в конце файла

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +            if (password != repeatPassword) {
Эту проверку можно вынести отдельно, например, до отправки формы. Я ранее писал про события, на которые можно подписаться. Почитай про событие onBlur для input-а - тогда проверка для email и password будет аналогичная

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +      let type = input.children[1].type;
```suggestion
      let type = input.children[1].type === 'email' ? 'email' : 'password';
      // и ниже ифаки переделать так:
      
      validationError = validate(e.target.value, type); // и убрать повторяющиеся куски в одну обертку
```

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +  togglePasswordVisibility(inputWithButton) {
Эта функция повторяется дважды. Реализуй отдельный класс FormBase и наследуй от него SignupForm и LoginForm

2024-03-20 14:53 UTC, mzingwrld commented on src/api/user.js
> +    console.error('Error: ', error); // улучшить обработку ошибок
Лучше оставлять 'TODO' - почти все IDE умеют с ними удобно работать)
А еще лучше не оставлять такое вообще)

```suggestion
    console.error('Error: ', error); // TODO: улучшить обработку ошибок
```

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
>        userHelper('set', response.User.username);
Чет я просмотрел эту функу на прошлых ревью.
По ней тоже есть трудности с пониманием.
1) название вообще не говорящее
2) внутри лучше переделать на switch

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +    }));
Этот кусок кода повторяется дважды - тоже можно вынести в FormBase класс, от которого наследоваться

2024-03-20 14:53 UTC, mzingwrld commented on src/utils/validation.js
> +export function validate(inputText, type) {
Еще, наверное, было бы правильно выбрасывать ошибку из функции validate с текстом ошибки, а если все ок, то просто ничего не делать. Тогда не нужно проверять на null при использовании функи

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +      this.renderError("Эта почта уже используется");
А норм что на "ок" рендер ошибки идет?

2024-03-20 14:53 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +        document.querySelectorAll('.input-button').forEach((input) => this.renderError(input, null)); // сомнительно но окэй
Можно вынести в метод типа `clearErrorMessage`

Почему сомнительно?

2024-03-20 17:22 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.hbs
> +        <input id="password" type="password" class="form-input" required maxlength="16" title="Пароль не может быть пустым и содержать пробелы" pattern="(?=.*\d)(?=.*[A-Z])(?!.*\s).{8,}">
UPD: эмоджи более не кушаются

2024-03-20 17:25 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +      errorMessage.classList.add('active');
Сделано

2024-03-20 19:11 UTC, exg0rd commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +      let type = input.children[1].type;
тут переделал логику поэтому неактуально

2024-03-20 19:12 UTC, exg0rd commented on src/api/user.js
> +    console.error('Error: ', error); // улучшить обработку ошибок
хорошо) немного по другому теперь работаю с функцией и обрабатываю ошибку

2024-03-20 19:12 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
>        userHelper('set', response.User.username);
убрал эту функцию вообще

2024-03-20 19:14 UTC, exg0rd commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +      this.renderError("Эта почта уже используется");
неактуально вроде теперь

2024-03-20 19:15 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +        document.querySelectorAll('.input-button').forEach((input) => this.renderError(input, null)); // сомнительно но окэй
показалось нерациональным изначально, будто проще можно было сделать а не явно очищать ошибки

2024-03-22 08:40 UTC, mzingwrld commented on src/components/Form/BaseForm.js
> +  });
Название функции не отражает его действительного действия
Плюс, помимо блокирования кнопки, метод выполняет валидацию полей и рендер ошибок (при том. только по паролю)

Я бы рекомендовал разместить всю валидацию в одном месте, не разделяя ее и тем более не скрывая в других функциях по частям)

Тут можно глянуть про SOLID, а конкретно Single Responsibility Principle

2024-03-22 08:41 UTC, mzingwrld commented on src/components/Form/BaseForm.js
> +class BaseForm {
Тут стоит подумать про нейминг получше) BaseForm звучит как класс, который можно использовать на любых формах, но далеко не каждая форма будет содержать в себе пароли

2024-03-22 10:39 UTC, exg0rd commented on src/components/Form/BaseForm.js
> +class BaseForm {
done

2024-03-22 10:40 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +        passwordVisibility.children[0].src = "static/visible.svg";
Сделано

2024-03-22 10:41 UTC, exg0rd commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +            if (password != repeatPassword) {
Обработчики есть

2024-03-22 10:45 UTC, exg0rd commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +            this.renderError(passwordRepeatInput.parentElement, response.error);
По идее валидация не дает вбить недопустимые поля, а рендер ошибки идет в repeatPasswordInput чтобы ошибка высвечивалась внизу формы (самой нижней)

2024-03-22 10:45 UTC, exg0rd commented on src/router/urls.js
> +  notfound: '',
done

2024-03-22 12:00 UTC, exg0rd commented on src/pages/SignupPage/SignupForm/SignupForm.js
> +          if (response.Code === undefined) {
Переделал

2024-03-22 12:01 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
>        userHelper('set', response.User.username);
А где?)

2024-03-26 10:43 UTC, mzingwrld requested changes

2024-03-26 10:43 UTC, mzingwrld commented on src/components/Form/AuthorizationForm.js
> +    const areErrors = (errorMessages.length > 0);
```suggestion
    const hasErrors = errorMessages.length > 0;
```

2024-03-26 10:43 UTC, mzingwrld commented on src/components/Placelist/Placelist.js
> +    const places = get('http://127.0.0.1:8080/sights', this.getPlaces.bind(this));
Почему тут env не используется?

2024-03-26 10:43 UTC, mzingwrld commented on src/pages/PlacesPage/Placelist/Place/star.js
> +export default starSvg;
Нужен прогон линтера

2024-03-26 10:43 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +            this.renderError(inputs[1], response.error);
А что за элемент по индексу 1?
Мб явно обратиться к нему через id?

2024-03-26 19:41 UTC, exg0rd commented on package.json
> +    "dotenv-webpack": "^8.1.0",
Я убрал его, немного переделал логику использования

2024-03-26 19:44 UTC, exg0rd commented on src/components/Form/AuthorizationForm.js
> +    const areErrors = (errorMessages.length > 0);
DONE

2024-03-26 20:23 UTC, exg0rd commented on src/pages/PlacesPage/Placelist/Place/star.js
> +export default starSvg;
ok

2024-03-26 20:23 UTC, exg0rd commented on package.json
> +    "dotenv-webpack": "^8.1.0",
без него не получилось

2024-03-27 04:02 UTC, mzingwrld approved these changes

2024-03-27 06:00 UTC, merged