ts refactor done, build problems
frontend-park-mail-ru/2024_1_ResCogitans pull request #13
Opened 2024-03-28 14:57 UTC by exg0rd

2024-03-30 03:20 UTC, mzingwrld requested changes

2024-03-30 03:20 UTC, mzingwrld commented on src/components/Header/Header.ts
> +        if (process.env.API_URL !== undefined) {
Каждый раз проверку на наличие API_URL в env не стоит делать.
Можно сделать константу envConfig.js, в которой у тебя будет такой объект

```javascript
export const ENV_CONFIG = {
    API_URL = proces..env.API_URL || 'NOT_PROVIDED',
}
```

2024-03-30 03:20 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.ts
> +      if (process.env.API_URL !== null && process.env.API_URL !== undefined) {
Здесь тоже проверку лучше убрать

2024-03-30 03:20 UTC, mzingwrld commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +interface Sight {
Заведи каталог с типами, которые возвращает бэк; Переиспользуй типы из одного места. Я вижу у тебя дважды `interface Sight`. Если будут какие-то изменения на бэкенде, хорошо бы менять это все в одном месте

2024-03-30 03:20 UTC, mzingwrld commented on src/router/router.ts
> +export { router };
Прогони линтер

2024-03-30 03:20 UTC, mzingwrld commented on tserr.txt
> +webpack 5.90.3 compiled with 3 errors in 2602 ms
Кажется, этот файл не нужно коммитить

2024-03-30 03:20 UTC, mzingwrld commented on src/components/Base/Base.ts
> +    }
Что-то странное, зачем оберка поверх preRender? Почему фактический render называется preRender?)

2024-03-30 03:20 UTC, mzingwrld commented on package.json
> +    "express-handlebars": "^7.1.2",
Зачем тебе эта зависимость?

2024-03-30 03:20 UTC, mzingwrld commented on tsconfig.json
>      // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */
Очень много выключенных настроек.

Давай хотя бы минимум включим, можно глянуть тут, например, https://github.com/tsconfig/bases/blob/main/bases/recommended.json

или почитать статьи по теме.

Также рекомендую реализовать alias-ы для импортов, чтобы по коду не было `import from '../../../file.js'`:

Для этого, существует paths свойство, пример:
```json
    "paths": {
      "@server/*": ["src/*"],
      "@tests/*": ["__tests__/*"],
      "@config/*": ["src/config/*"],
      "@domain/*": ["src/domain/*"],
      "@controller/*": ["src/controller/*"],
      "@middleware/*": ["src/middleware/*"]
    }
```

2024-03-30 03:20 UTC, mzingwrld commented on tsconfig.json
>      // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */
Или еще пример, как мы на проекте в почте элиасы используем:

```json
    "paths": {
      "@/*": ["src/*"],
    }
```

2024-03-30 03:20 UTC, mzingwrld commented on tsconfig.json
>      // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */
От себя рекомендую включить следующие правила:

```json
{
        "strict": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "sourceMap": true,
        "skipLibCheck": true,
        "experimentalDecorators": true,
        "strictNullChecks": true,
        "noImplicitAny": true,
}
```

2024-03-30 10:22 UTC, exg0rd commented on src/components/Base/Base.ts
> +    }
Это рендер шаблона, а в самом рендере добавление иных компонентов и навешивание логики. В таком случае можно вынести это в отдельный метод базовый, а рендер специализировать в каждом классе

2024-04-01 10:39 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.ts
> +      if (process.env.API_URL !== null && process.env.API_URL !== undefined) {
Done

2024-04-01 19:31 UTC, exg0rd commented on package.json
> +    "express-handlebars": "^7.1.2",
убрал

2024-04-01 19:31 UTC, exg0rd commented on tserr.txt
> +webpack 5.90.3 compiled with 3 errors in 2602 ms
убрал)

2024-04-01 19:32 UTC, exg0rd commented on src/components/Header/Header.ts
> +        if (process.env.API_URL !== undefined) {
done

2024-04-02 05:16 UTC, mzingwrld commented on src/api/user.ts
> +export async function login(url : string, body : any): Promise<any> {
Накинь драфт-пример что ты имеешь ввиду тут в виде коммента, не очень понял :)

2024-04-02 06:02 UTC, exg0rd commented on src/api/user.ts
> +export async function login(url : string, body : any): Promise<any> {
В user сейчас есть функция authorize

2024-04-02 06:21 UTC, mzingwrld requested changes

2024-04-02 06:21 UTC, mzingwrld commented on src/api/user.ts
> +export async function login(url : string, body : any): Promise<any> {
Да, увидел, как сделал - норм)
Если расхождения начнутся между единообразным подходом, посмотришь еще раз)

2024-04-02 13:26 UTC, exg0rd commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +interface Sight {
Done

2024-04-02 13:26 UTC, exg0rd commented on src/router/router.ts
> +export { router };
Done + precommit hook

2024-04-02 15:56 UTC, mzingwrld approved these changes

2024-04-10 03:25 UTC, merged