Rk2
frontend-park-mail-ru/2024_1_ResCogitans pull request #16
Opened 2024-04-12 06:04 UTC by exg0rd

2024-04-12 16:13 UTC, mzingwrld requested changes

2024-04-12 16:13 UTC, mzingwrld commented on src/pages/SightPage/SightPage.ts
> +export default SightPage;
А дай скрин или видос как оно работает сейчас, пожалуйста

2024-04-12 16:13 UTC, mzingwrld commented on src/pages/SightPage/SightPage.ts
> +          router.go('login');
постоянно эти проверки - это вообще не ок)

2024-04-12 16:13 UTC, mzingwrld commented on src/pages/SightPage/SightPage.ts
> +      post(`sight/${this.id}/create`, requestBody).then((responseCreateReview) => {
нужно выносить это (и все подобное) в /api каталог и вызывать в виде `createSight(payload: ...)`

и зачем нужен id при создании - его же бэк должен выдать тебе?

2024-04-12 16:13 UTC, mzingwrld commented on src/pages/SightPage/SightPage.ts
> +    cancelButtons.forEach((button : HTMLButtonElement) => button.addEventListener('click', function () {
я бы рекомендовал сущность, которая управляет комментариями, вынести в отдельный компонент

например, `ReviewsWrapper`

в нем реализовать удаление, редактирование и т.п.

так будет проще изолированно работать с ней

а тут сечас проблемно выделять логику sight от review

2024-04-12 16:13 UTC, mzingwrld commented on src/pages/SightPage/SightPage.ts
> +        window.location.reload();
ну перезагрузка страницы происходит же именно по этой причине, не?) (то, о чем ты говорил на созвоне)

2024-04-12 16:13 UTC, mzingwrld commented on src/pages/ProfilePage/PreviewJourney.ts
> +export default previewJourney;
прогони линтер)

2024-04-14 15:03 UTC, exg0rd commented on src/pages/JourneyPage/JourneyPage.ts
> +      this.isOwn = (localStorage.getItem('username') === this.journey.id);
Тут очепятка, бэк возвращает айди и юзернейм, сравнивать надо одинаковые поля из локалстораджа и из ответа

2024-04-14 15:17 UTC, exg0rd commented on src/pages/JourneyPage/JourneyPage.ts
> +        router.go('login');
Короче выходит так что пока нет страниц где железно нужна авторизация, есть вариация страницы - создание\редактирование поездки

2024-04-15 07:24 UTC, exg0rd commented on src/pages/SightPage/SightPage.ts
> +        window.location.reload();
Это убрано

2024-04-15 07:24 UTC, exg0rd commented on src/pages/ProfilePage/PreviewJourney.ts
> +export default previewJourney;
Прогоняю

2024-04-15 07:34 UTC, mzingwrld requested changes

2024-04-15 07:43 UTC, exg0rd commented on src/pages/JourneyPage/JourneyPage.ts
> +    }
Поменял немного

2024-04-15 07:45 UTC, exg0rd commented on src/pages/JourneyPage/JourneyPage.ts
> +          router.go('login');
Решили вопрос в тг

2024-04-15 07:46 UTC, exg0rd commented on src/utils/localstorage.ts
> +export function authUser(username: string, id : number) {
fix

2024-04-15 08:01 UTC, exg0rd commented on src/pages/ProfilePage/ProfilePage.ts
> +        });
Сделал последовательно

2024-04-15 08:02 UTC, exg0rd commented on src/pages/ProfilePage/ProfilePage.ts
> +      post(`profile/${this.userdata.id}/edit`, profileRequestBody).then(() => {
Добавил проверку на ошибки

2024-04-15 08:49 UTC, exg0rd commented on src/pages/JourneyPage/JourneyPage.ts
> +              router.go(`journey/edit/${this.tripID}`);
Сделал что-то похожее)

2024-04-15 09:08 UTC, mzingwrld requested changes

2024-04-15 09:08 UTC, mzingwrld commented on src/pages/ProfilePage/ProfilePage.ts
> +      });
Еще одно место с нехорошим поведением:

Если первый запрос выполнится, а у пользователя медленный инет и он начнет жмакать на кнопки или уйдет вообще со страницы - часть запросов будет прервана, либо будут вызваны дополнительные

Это может спровоцировать неожиданное поведение

Как такое можно обработать?

2024-04-15 09:08 UTC, mzingwrld approved these changes

2024-04-15 10:53 UTC, merged