added types for responses
frontend-park-mail-ru/2024_1_ResCogitans pull request #19
Opened 2024-04-17 18:32 UTC by sp20ks

Что было не так:

- ответы апи не были типизированы

Что сделано:

- немного поправлены уже имеющиеся интерфейсы, добавлены новые

2024-04-17 18:36 UTC, exg0rd commented on src/pages/ProfilePage/ProfilePage.ts
> +    console.log(profileData);
логи не забывай убирать)

2024-04-17 18:38 UTC, exg0rd commented on src/types/api.ts
> +  error: string,
а это для чего?

2024-04-17 18:39 UTC, exg0rd commented on src/types/api.ts
> +  error: string,
а это для чего?

2024-04-18 04:47 UTC, mzingwrld requested changes

2024-04-18 04:47 UTC, mzingwrld commented on src/types/api.ts
> +export interface SightResponse {
Почему JourneyResponse и SightResponse не через generic WithResponse используются?

2024-04-18 04:47 UTC, mzingwrld commented on src/pages/ProfilePage/ProfilePage.ts
> +    const journeyList = await get(`${this.userdata.id}/trips`) as WithResponse<{ journeys: Journey[] }>;
Предлагал Егору вынести подобные методы в api каталог в формате:

`trips.ts -> getUserTrips(userId: number) => ...`
Не нужно будет тогда делать `as blablah..` и в коде далее просто вызов будет `await getUserTrips(this.userdata.id);`

Еще из интересного: получаем trips, а в typing-ах journey - немного не состыковались бэк и фронт и было бы круто одинаково называть сущности для удобства

2024-04-18 04:47 UTC, mzingwrld commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +    const response = await get('sights') as WithResponse<{ sights: Sight[] }>;
Повторы по коду увидел (два раза точно): уже заслуживает вынесения в отдельный тип)
```suggestion
    // types/api.ts
    type Sights = {
        sights: Sight[];
    }
    
    const response = await get('sights') as WithResponse<Sights>;
```

2024-04-18 17:54 UTC, sp20ks commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +    const response = await get('sights') as WithResponse<{ sights: Sight[] }>;
поправила

2024-04-18 17:55 UTC, sp20ks commented on src/pages/ProfilePage/ProfilePage.ts
> +    const journeyList = await get(`${this.userdata.id}/trips`) as WithResponse<{ journeys: Journey[] }>;
поправила


насчет нейминга. мне почему-то кажется, что это будет проще поправить на стороне гошки, так как в бд у нас таблица journey. где-то в респонсах там затерялся trips

2024-04-18 17:56 UTC, sp20ks commented on src/types/api.ts
> +export interface SightResponse {
и это поправила

2024-04-19 06:05 UTC, mzingwrld requested changes

2024-04-19 06:05 UTC, mzingwrld commented on src/api/user.ts
> +  return await post(ROUTES.profile.reset_password(userId), { password: password }) as WithResponse<UserProfile>;
А почему у нас тут ROUTES появились? Это же константа чисто для роутинга по страницам

в src/api/sight.ts и в src/api/journey.ts ты пишешь обращение к бэку в виде строк, а тут так - не понимаю)

2024-04-26 15:37 UTC, mzingwrld approved these changes

2024-04-26 18:03 UTC, merged