added filter by category
frontend-park-mail-ru/2024_1_ResCogitans pull request #25
Opened 2024-04-28 22:30 UTC by sp20ks

2024-05-03 04:17 UTC, mzingwrld requested changes

2024-05-05 05:07 UTC, sp20ks commented on src/api/sight.ts
> +  const url = `sight/quiz?${queryString}`;
неа. это ручка, которая отвечает за поиск по sights. название немного неочевидное, согласна

2024-05-05 05:08 UTC, sp20ks commented on src/components/MainSearch/MainSearch.ts
> +      if (event.key === 'Enter') {
кнопка есть. прям чуть ниже я добавляю обработчик событий на main-search-button

2024-05-05 05:59 UTC, sp20ks commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +  }
поправила

2024-05-05 06:09 UTC, mzingwrld requested changes

2024-05-05 06:09 UTC, mzingwrld commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +    let queryParams: { [key: string]: any } = {};
Лучше никогда не использовать any
Лучше подходит unknown и потом сужать тип проверками, но any - зло :)

2024-05-05 06:10 UTC, mzingwrld commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +    let queryParams: { [key: string]: any } = {};
И рядом везде any лучше убрать тоже

2024-05-05 06:25 UTC, sp20ks commented on src/pages/PlacesPage/Placelist/Placelist.ts
> +    let queryParams: { [key: string]: any } = {};
поправила

2024-05-05 06:28 UTC, mzingwrld approved these changes

2024-05-05 06:29 UTC, merged