Альбомы с сущностью
frontend-park-mail-ru/2024_1_ResCogitans pull request #26
Opened 2024-05-03 16:07 UTC by exg0rd

Что работает:

1) Просмотр альбома
2) Создание нового альбома
3) Изменение альбома 

* Свайпы на мобильных устройствах
* Карусель мышкой и стрелочками
* фулскрин модалка с описаниями и Фото n из m
* Изменение и создание описаний

Чего нет: проверки интеграции с бекэндом, сделать фото главным - будет отображаться в карточке альбома кругом
(будет работать через события + отдельный запрос с айди фото)

Принцип работы: состояние альбома через сущности фото - при удалении старого фото (изменение) происходит перерасчёт айди и будет отправляться запрос на удаление старого фото. При загрузке фото добавляется в формдату. 
Конечный будет состоять из форм дат, по которым бэкенд должен сам загрузить фото в альбом.

2024-05-05 06:26 UTC, mzingwrld requested changes

2024-05-05 06:26 UTC, mzingwrld commented on src/api/album.ts
> +export async function getAlbum(albumID : number) {
Речь про неоднобразный нейминг
```suggestion
export async function getUserAlbums(userId: number) { // тут userId
  return await get(`profile/${userId}/albums`) as WithResponse<{ albums: AlbumData[] }>;
}

export async function getAlbum(albumId : number) { // а тут было почему то albumID
```

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/AlbumPage/AlbumPage.ts
> +            } else if (files[i].size > 8388608) { // 8 Mb
```suggestion
const EIGHT_MB_IN_BYTES = 8388608;
...
            } else if (files[i].size > EIGHT_MB_IN_BYTES) {
```

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/AlbumPage/AlbumPage.ts
> +              console.log('here');
дебаг штуки лучше убирать)

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/AlbumPage/AlbumPage.ts
> +          }
тоже, наверное не нужно оставлять

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/AlbumPage/AlbumPage.ts
> +export default AlbumPage;
Файл на 400 строк получился.

Предлагаю попробовать extract-нуть какой-то функционал в utils файл и попробовать вытащить логику, которая, например, отвечает за перелистывание, модалки и swipe

Сейчас файл очень трудно читать и понимать где и что тут происходит - попробуешь порефачить?

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/AlbumPage/AlbumPhoto.ts
> +        deleteEvent.stopImmediatePropagation();
Это плохая практика

Лучше делать preventDefault(), а в остальных хендлерах проверку делать if(!defaultPrevented) {...}


Чтобы понять почему так:
представь что ты разработчик библиотеки компонентов и ты, работая с событиями, останавливаешь их propagation - это будет неожиданно для разработчика, который использует либу.
В общем, это плохо)

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/ProfilePage/ProfilePage.ts
> +          this.createElement('h3', {}, this.isOwn ? 'Вы пока не создавали альбомы' : 'Пользователь пока не создавал альбомы', {
Блок дважды повторяется - можно переиспользовать?

2024-05-05 06:26 UTC, mzingwrld commented on src/pages/AlbumPage/AlbumPage.ts
> +export default AlbumPage;
Потом внимательнее еще посмотрю)

2024-05-05 19:09 UTC, exg0rd commented on src/api/album.ts
> +export async function getAlbum(albumID : number) {
Исправил названия

2024-05-05 19:11 UTC, exg0rd commented on src/pages/AlbumPage/AlbumPage.ts
> +            } else if (files[i].size > 8388608) { // 8 Mb
fix magic number

2024-05-05 19:12 UTC, exg0rd commented on src/pages/AlbumPage/AlbumPage.ts
> +              console.log('here');
само собой но я после пр собирался идти интегрировать с бком поэтому оставил)
убрал пока

2024-05-05 19:12 UTC, exg0rd commented on src/pages/AlbumPage/AlbumPage.ts
> +          }
fix

2024-05-05 19:13 UTC, exg0rd commented on src/pages/AlbumPage/AlbumPhoto.ts
> +        deleteEvent.stopImmediatePropagation();
этот функционал оказался не нужен

2024-05-05 19:13 UTC, exg0rd commented on src/pages/ProfilePage/ProfilePage.ts
> +          this.createElement('h3', {}, this.isOwn ? 'Вы пока не создавали альбомы' : 'Пользователь пока не создавал альбомы', {
исправил

2024-05-06 06:53 UTC, mzingwrld approved these changes

2024-05-06 07:13 UTC, merged