Routing
frontend-park-mail-ru/2024_1_ResCogitans pull request #5
Opened 2024-03-10 09:35 UTC by exg0rd

Формы логина и регистрации на новых страницах

2024-03-10 17:29 UTC, mzingwrld requested changes

2024-03-10 17:29 UTC, mzingwrld commented on src/components/Header/Header.js
> +          router.go(urls.sights);
этот колбэк можно вынести в отдельную функцию внутри хидер класса с понятным неймингом

2024-03-10 17:29 UTC, mzingwrld commented on src/components/Header/Header.js
> +      document.getElementById('button-login').addEventListener('click', () => {
```suggestion
      loginButton.addEventListener('click', () => {
```

2024-03-10 17:29 UTC, mzingwrld commented on src/components/MainSearch/MainSearch.hbs
> +    <h1>КУДА ПУТЬ ДЕРЖИМ?</h1>
капс - ок?

2024-03-10 17:29 UTC, mzingwrld commented on src/index.js
>  });
```suggestion
router.register(routes);
```

2024-03-10 17:29 UTC, mzingwrld commented on src/index.js
> +  startingPath = urls.sights;
почему бы sights не оставить на корне?

2024-03-10 17:29 UTC, mzingwrld commented on src/index.js
> +  console.log(startingPath);
это нужно? если все логи были нужны для отладки, то стоит убрать

2024-03-10 17:29 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +      new Link(loginForm, {id: 'form-error', className: "err-link", label: response.error}).render();
обработку ошибок лучше делать в catch блоке

2024-03-10 17:29 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +      login("http://jantugan.ru", {username: username, password: password}, this.displayErrorOrRedirect);
```suggestion
      login("http://jantugan.ru", {username, password}, this.displayErrorOrRedirect);
```

2024-03-10 17:29 UTC, mzingwrld commented on src/pages/SignupPage/SignupPage.js
обертка очень похожа на LoginPage - отличаются только рендером

2024-03-10 17:29 UTC, mzingwrld commented on src/router/Router.js
> +        content.innerHTML = "";
можно вынести в отдельный метод

2024-03-10 17:29 UTC, mzingwrld commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +      localStorage.setItem('username', response.User.username);
сделайте на бэке лучше так, чтобы все было с маленькой буквы - выглядит оч странно)

```suggestion
      localStorage.setItem('username', response.user.username);
```

2024-03-10 18:36 UTC, exg0rd commented on src/api/api.js
> +export { get };
✅

2024-03-10 18:36 UTC, exg0rd commented on src/components/Button/Button.js
> +    return (document.getElementById(this.id))
✅

2024-03-10 18:39 UTC, exg0rd commented on src/components/Header/Header.css
> +    font-size: 1.5rem;
Вообще я думал что они сохраняют масштабирование шрифта например в мобильной версии, потому что раньше шрифты при уменьшении ширины становились больше, а сейчас нет.

2024-03-10 18:42 UTC, exg0rd commented on src/index.js
> +});
✅

2024-03-10 18:43 UTC, exg0rd commented on src/router/Router.js
> +            return;
Да, смысла нет переделывать страницу при совпадении урлов

2024-03-10 18:45 UTC, exg0rd commented on src/router/routes.js
> +    },
✅

2024-03-10 18:45 UTC, exg0rd commented on webpack.config.js
> +      'process.env.HOST_NAME': JSON.stringify('https://localhost:8080'),
Пытался настроить dot env

2024-03-10 19:25 UTC, exg0rd commented on src/router/Router.js
> +            // notFoundPage.render();
✅

2024-03-10 19:29 UTC, exg0rd commented on src/router/Router.js
> +    changeLocation() {
✅

2024-03-10 19:31 UTC, exg0rd commented on public/index.html
> +        </div>
Для удобства

2024-03-10 19:32 UTC, exg0rd commented on public/index.html
> +    <script src="bundle.js" defer></script>
Не убрал после ресёрча

2024-03-10 19:52 UTC, exg0rd commented on src/api/api.js
> +        const content = await response.json();
✅

2024-03-10 19:54 UTC, exg0rd commented on src/router/Router.js
> +        content.innerHTML = "";
✅

2024-03-10 19:55 UTC, exg0rd commented on src/pages/LoginPage/LoginForm/LoginForm.js
> +      login("http://jantugan.ru", {username: username, password: password}, this.displayErrorOrRedirect);
✅

2024-03-10 19:55 UTC, exg0rd commented on src/index.js
> +  console.log(startingPath);
Не нужно

2024-03-10 19:57 UTC, exg0rd commented on src/index.js
> +  startingPath = urls.sights;
✅

2024-03-10 19:57 UTC, exg0rd commented on src/index.js
>  });
✅

2024-03-10 20:01 UTC, exg0rd commented on src/components/MainSearch/MainSearch.hbs
> +    <h1>КУДА ПУТЬ ДЕРЖИМ?</h1>
✅ но вообще дизайнерское решение

2024-03-10 20:04 UTC, exg0rd commented on src/components/Header/Header.js
> +      document.getElementById('button-login').addEventListener('click', () => {
✅

2024-03-10 20:06 UTC, exg0rd commented on src/components/Header/Header.js
> +          router.go(urls.sights);
не понимаю смысла пока

2024-03-10 20:09 UTC, sp20ks commented on src/components/MainSearch/MainSearch.hbs
> +    <h1>КУДА ПУТЬ ДЕРЖИМ?</h1>
не баг, а фича

2024-03-11 04:12 UTC, mzingwrld commented on src/components/Header/Header.css
> +    font-size: 1.5rem;
Может тогда rollback на pixels?

2024-03-11 04:13 UTC, mzingwrld commented on public/index.html
> +        </div>
Сразу возникает много вопросов)

Если это нужно роутеру, то пусть он и создает этот div в #root элемент

2024-03-11 04:13 UTC, mzingwrld commented on src/api/api.js
> +    }
А как сейчас бэкенд ошибки возвращает? Если в 200-ом коде, то это не нормально

2024-03-11 04:14 UTC, mzingwrld commented on src/components/Header/Header.js
> +          router.go(urls.sights);
Улучшает читаемость кода

2024-03-11 04:31 UTC, mzingwrld requested changes

2024-03-11 04:31 UTC, mzingwrld commented on .eslintignore
> +docs/
```suggestion
docs/

```

2024-03-11 04:31 UTC, mzingwrld commented on src/api/user.js
> +    callback(data, null);
Зачем тут вторым аргументов null передается?

2024-03-11 04:31 UTC, mzingwrld commented on src/index.js
> +router.go(startingPath);
Кажется, что теперь можно просто оставить так:
```suggestion
router.go(window.location.pathname);
```

2024-03-11 04:33 UTC, mzingwrld commented
Нужно устранить конфликты и обсудить в рамках какого PR будете фиксить замечания которые я оставил к PR Эмиля

+ зафиксировать остальные правки в виде задач в бэклоге, если сейчас не планируется их исправлять (можно в одну задачу закинуть все, просто в тредах отписаться "будет пофикшено в рамках <link to trello task>"

2024-03-11 07:40 UTC, exg0rd commented on public/index.html
> +        </div>
done

2024-03-11 07:40 UTC, exg0rd commented on src/api/api.js
> +    }
не в 200, обсудили

2024-03-11 07:41 UTC, exg0rd commented on src/api/user.js
> +    callback(data, null);
fix

2024-03-11 07:42 UTC, exg0rd commented on src/index.js
> +router.go(startingPath);
fixed

2024-03-11 07:53 UTC, exg0rd commented on src/components/Header/Header.js
> +          router.go(urls.sights);
вынес в utils

2024-03-11 07:55 UTC, mzingwrld commented on src/components/Header/Header.js
> +          router.go(urls.sights);
Она должна быть в виде property класса Header :)

2024-03-13 17:18 UTC, closed without merging